psalm checks and phpunit with more NC versions
Signed-off-by: Julien Veyssier <julien-nc@posteo.net>

diff --git a/.github/workflows/psalm.yml b/.github/workflows/psalm.yml
--- a/.github/workflows/psalm.yml
+++ b/.github/workflows/psalm.yml
@@ -34,24 +34,48 @@ concurrency:
 jobs:
   static-analysis:
     runs-on: ubuntu-latest
+    strategy:
+      # do not stop on another job's failure
+      fail-fast: false
+      matrix:
+        ocp-version: ['30', 'dev-master']
+        php-version: ['8.1', '8.2', '8.3']
 
-    name: Psalm check
+
+    name: Psalm, PHP ${{ matrix.php-version }}, OCP ${{ matrix.ocp-version }}
     steps:
       - name: Checkout
-        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
       - name: Set up php
-        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
+        uses: shivammathur/setup-php@7fdd3ece872ec7ec4c098ae5ab7637d5e0a96067 # v2
         with:
-          php-version: 8.2
+          php-version: ${{ matrix.php-version }}
           coverage: none
           ini-file: development
-          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, gd, zip
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Install dependencies
         run: composer i
 
+      - name: Install dependencies
+        run: composer require --dev nextcloud/ocp:${{ matrix.ocp-version }} --ignore-platform-reqs --with-dependencies
+
+      - name: Install dependencies
+        run: composer require --dev
+
       - name: Run coding standards check
         run: composer run psalm
+
+  summary:
+    runs-on: ubuntu-latest
+    needs: static-analysis
+
+    if: always()
+
+    name: static-psalm-analysis-summary
+
+    steps:
+      - name: Summary status
+        run: if ${{ needs.static-analysis.result != 'success' }}; then exit 1; fi
